---
title: "General guidelines"
output: html_document
---


## About the expert survey
You are being invited to participate in an expert survey regarding the instruments of direct democracy in your country. The questionnaire is completed via the online coding platform.

In the My Jobs tab you will find 7 jobs (i.e., questionnaires) -one for each instrument of direct democracy. A questionnaire is structured around a series of Items (questions) where each Item has three corresponding attributes:  
&nbsp;&nbsp;(a) The answer to the actual Item (question)  
&nbsp;&nbsp;(b) The legal source  
&nbsp;&nbsp;(c) A Comments/Remarks box where you can leave a comment to the team.
<br/><br/>

## Answering the questionnaire  

1. Please fill out all 7 questionnaires (jobs) based on the legal rules of your country at national level.  
-If the direct democratic instrument does not exist in your country, please answer question 1 with "no", which would bring you directly to the last question of the questionnaire. This last question of questionnaire is about the existence of the instrument at subnational level, which may be relevant even if the instrument does not exist at national level.

2. Please answer the questions based on the legal rules of your country.  
-In general, you are not expected to research the legal practice of the rules, but if you happen to know the relevant practice, please indicate it in the comments section.

3. Please provide a legal source for every answer you give.  
-You do not need to cite the legal source, it is enough to point to the precise article of the constitution or the relevant legal act (e.g.: Article 34 (2) of the Act on Initiating Referendums).  
-If you are unable to point to a legal source, please clarify the reason for that in the comments section or indicate the source of your information there.

4. One instrument may have different versions in a country (e.g. agenda proposal with different number of signatures required, depending on whether the proposal concerns the constitution or a piece of legislation, etc.). The following solutions are available to reflect such differences:  
-If the legal rules are significantly different for the different versions: A and B versions will be created, so both versions can be coded separately. We created the A and B versions in advance for the cases known to us, so you should already see this when you sign in to the coding platform. In case an instrument in your country has more versions with different rules and you do not have A and B versions, please let us know.  
-If the legal rules only differ in one variable (e.g. the number of signatures): please code according to the version that is more common in use and indicate the other in the comments.  
-OR code according to the more restrictive version (e.g. the one requiring more signatures) and indicate the other in the comments.

5. If you have any technical difficulty with the platform, please contact Fernando Mendez (fmendez72@gmail.com).  
If you have any further questions about the meaning or scope of the instruments or the questions, please contact Anna Forgacs (anna.forgacs@uzh.ch) or Henri Ibi (henri.ibi@uzh.ch)
<br/><br/>

### Specific issues to note

1. Proactive and rejective citizens’ initiatives: if there is only one set of rules for referendums initiated by citizens in your country, but the instrument can be used both to suggest a topic for a referendum (proactive) and to initiate a referendum that is aimed at preventing a constitutional amendment or a legislative act from being passed or at abolishing it (rejective), then please code it as both proactive  and rejective initiative.

2. Ad hoc legislature-initiated referendums: if there are no general rules about the legislature as an initiator of referendums, but it is possible that the legislature adopts an ad hoc act about calling a referendum on a certain issue, then please code it as a "yes" for the instrument existing and “no” for the clear legal basis.

3. Procedural questions (e.g. hearing rights, evidence): please code according to the first-instance procedure, but indicate in the comments if there are significant differences in the remedy procedure.  
-e.g. the first instance procedure is at the election commission where the applicants have hearing rights (code this), but there is a remedy to the court where the applicants do not have hearing rights (put this into comment).

4. Questions regarding the practice of rejective, proactive referendums and agenda initiatives: the availability of statistical information regarding the launched and authorised initiatives may vary in each country. This type of information is most likely to be available on the website of the state institution deciding about the formal and/or substantive admissibility of the issue/question. If you are able to find such statistical information, please indicate the source of the information in the comments section. If the statistical data is available on a website, please copy the link of the website into the comments section.
